<template>
  <div class="page-title"><div><h1>扩展管理</h1><p>上传、绑定并同步浏览器扩展</p></div><el-button type="primary" @click="openCreate">新增扩展</el-button></div>
  <div class="panel"><div class="toolbar extension-filters"><el-input v-model="keyword" placeholder="搜索名称、code、提供方" clearable @change="load" style="width:360px"/><el-select v-model="kernel" placeholder="内核" clearable @change="load" style="width:180px"><el-option label="Chromium" value="chrome"/><el-option label="Firefox" value="firefox"/></el-select></div>
    <el-table :data="items" v-loading="loading"><el-table-column prop="name" label="名称"/><el-table-column prop="code" label="Code"/><el-table-column prop="version" label="版本"/><el-table-column prop="browser_kernel" label="内核"/><el-table-column label="类型"><template #default="{row}">{{ row.extension_type === 'builtin' ? '内置' : '普通' }}</template></el-table-column><el-table-column label="绑定环境"><template #default="{row}">{{ row.environment_codes.includes('*') ? '全部' : row.environment_codes.length }}</template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button link type="primary" @click="edit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table>
  </div>
  <el-dialog v-model="visible" :title="editing ? '编辑扩展' : '新增扩展'" width="620px"><el-form label-width="100px"><el-form-item label="Code"><el-input v-model="form.code" :disabled="editing"/></el-form-item><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="版本"><el-input v-model="form.version"/></el-form-item><el-form-item label="内核"><el-radio-group v-model="form.browser_kernel"><el-radio value="chrome">Chromium</el-radio><el-radio value="firefox">Firefox</el-radio></el-radio-group></el-form-item><el-form-item label="插件类型"><el-radio-group v-model="form.extension_type"><el-radio value="normal">普通</el-radio><el-radio value="builtin">内置</el-radio></el-radio-group></el-form-item><el-form-item label="提供方"><el-input v-model="form.provider"/></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea"/></el-form-item><el-form-item label="绑定环境"><el-checkbox v-model="form.bind_all">全部环境</el-checkbox><el-select v-if="!form.bind_all" v-model="form.environment_codes" multiple filterable style="width:100%"><el-option v-for="env in environments" :key="env.code" :label="env.name" :value="env.code"/></el-select></el-form-item><el-form-item label="ZIP 文件"><el-upload :auto-upload="false" :limit="1" :on-change="fileChanged" accept=".zip"><el-button>选择 ZIP</el-button></el-upload></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { ElMessage, ElMessageBox, type UploadFile } from 'element-plus'; import { api, apiForm, query } from '../api/client'; import type { Environment, Extension, Page } from '../types'
const items=ref<Extension[]>([]), environments=ref<Environment[]>([]), loading=ref(false), saving=ref(false), visible=ref(false), editing=ref(false), keyword=ref(''), kernel=ref(''), file=ref<File>(); const form=reactive<any>({code:'',name:'',version:'',browser_kernel:'chrome',extension_type:'normal',provider:'',description:'',environment_codes:[],bind_all:false})
async function load(){ loading.value=true; try{ const r=await api<Page<Extension>>(query('/open/extension/list',{page:1,page_size:100,keyword:keyword.value,browser_kernel:kernel.value})); items.value=r.items }finally{loading.value=false} }
async function loadEnvs(){ const r=await api<Page<Environment>>(query('/open/env/list',{page:1,page_size:100,keyword:''})); environments.value=r.items }
function reset(){ Object.assign(form,{code:'',name:'',version:'',browser_kernel:'chrome',extension_type:'normal',provider:'',description:'',environment_codes:[],bind_all:false}); file.value=undefined; editing.value=false }
function openCreate(){ reset(); visible.value=true }; function edit(row:Extension){ reset(); Object.assign(form,row,{bind_all:row.environment_codes.includes('*'),environment_codes:row.environment_codes.filter(x=>x!=='*')}); editing.value=true; visible.value=true }
function fileChanged(upload:UploadFile){ file.value=upload.raw }
async function save(){ saving.value=true; try{ const fd=new FormData(); for(const k of ['code','name','version','browser_kernel','extension_type','provider','description']) fd.append(k,String(form[k]??'')); fd.append('environment_codes',JSON.stringify(form.bind_all?['*']:form.environment_codes)); if(file.value) fd.append('file',file.value); await apiForm(editing.value?'/open/extension/update':'/open/extension/create',fd); ElMessage.success('保存成功'); visible.value=false; await load() }catch(e:any){ElMessage.error(e.message)}finally{saving.value=false} }
async function remove(row:Extension){ try{ await ElMessageBox.confirm('确认删除该扩展？','提示',{type:'warning'}); await api('/open/extension/delete',{code:row.code}); await load(); ElMessage.success('已删除') }catch(e:any){ if(e!=='cancel') ElMessage.error((e as any).message||String(e)) } }
onMounted(()=>{load();loadEnvs()})
</script>
